/**
 * Gradient Sweep - analog time shown as two overlapping rotating gradient discs.
 *
 * Each disc is a conic gradient, 100% opaque at its hand and fading (logarithmically
 * or linearly, by setting) to 0% over 225 degrees: the hour disc clockwise, the minute disc counter-clockwise.
 * The minute disc is layered over the hour disc.
 *
 * Rendered per pixel into the framebuffer with ordered dithering, so the
 * 4-levels-per-channel Pebble palette still yields smooth gradients.
 * Redraws once a minute only.
 */

#include <pebble.h>

#if !defined(PBL_COLOR)
#error "Gradient Sweep draws into an 8-bit color framebuffer; black-and-white platforms (aplite, diorite, flint) are not supported"
#endif

#define SETTINGS_KEY 2

#define SHAPE_CIRCLE 0        // hour wedge is contained by a circle
#define SHAPE_RECT 1          // ...or by an inset rectangle (a square on round watches)

// The hour container is two thirds of the screen: of the narrowest dimension
// for a circle (diameter), of each dimension for a rectangle.
// Disc opacity (out of 255) by distance from the hand, one entry per 256 trig-angle units.
// Both peak at 100% and reach 0 at 225 degrees. The logarithmic ramp keeps the discs dark
// longer than the linear one. Generated by preview/gen_lut.py.
#define DISC_RAMP_STEPS 160
static const uint8_t DISC_LUT_LOG[DISC_RAMP_STEPS] = {
  255, 254, 254, 253, 252, 251, 250, 250, 249, 248, 247, 247, 246, 245, 244, 243,
  243, 242, 241, 240, 239, 239, 238, 237, 236, 235, 234, 233, 233, 232, 231, 230,
  229, 228, 227, 226, 225, 225, 224, 223, 222, 221, 220, 219, 218, 217, 216, 215,
  214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204, 203, 202, 201, 200, 198,
  197, 196, 195, 194, 193, 192, 190, 189, 188, 187, 186, 185, 183, 182, 181, 180,
  178, 177, 176, 174, 173, 172, 170, 169, 168, 166, 165, 164, 162, 161, 159, 158,
  156, 155, 153, 152, 150, 149, 147, 146, 144, 142, 141, 139, 137, 136, 134, 132,
  130, 129, 127, 125, 123, 121, 119, 117, 115, 113, 111, 109, 107, 105, 103, 101,
  99, 96, 94, 92, 89, 87, 85, 82, 80, 77, 74, 72, 69, 66, 64, 61,
  58, 55, 52, 49, 45, 42, 39, 35, 32, 28, 24, 21, 17, 13, 9, 4,
};

static const uint8_t DISC_LUT_LINEAR[DISC_RAMP_STEPS] = {
  255, 253, 252, 250, 249, 247, 245, 244, 242, 241, 239, 237, 236, 234, 233, 231,
  230, 228, 226, 225, 223, 222, 220, 218, 217, 215, 214, 212, 210, 209, 207, 206,
  204, 202, 201, 199, 198, 196, 194, 193, 191, 190, 188, 186, 185, 183, 182, 180,
  178, 177, 175, 174, 172, 171, 169, 167, 166, 164, 163, 161, 159, 158, 156, 155,
  153, 151, 150, 148, 147, 145, 143, 142, 140, 139, 137, 135, 134, 132, 131, 129,
  128, 126, 124, 123, 121, 120, 118, 116, 115, 113, 112, 110, 108, 107, 105, 104,
  102, 100, 99, 97, 96, 94, 92, 91, 89, 88, 86, 84, 83, 81, 80, 78,
  77, 75, 73, 72, 70, 69, 67, 65, 64, 62, 61, 59, 57, 56, 54, 53,
  51, 49, 48, 46, 45, 43, 41, 40, 38, 37, 35, 33, 32, 30, 29, 27,
  25, 24, 22, 21, 19, 18, 16, 14, 13, 11, 10, 8, 6, 5, 3, 2,
};

#define CONTAINER_NUM 2
#define CONTAINER_DEN 3


typedef struct {
  uint8_t hour_rgb[3];  // darkest tone of the hour disc
  uint8_t min_rgb[3];
  uint8_t ramp;         // RAMP_*: shape of the opacity fade
  uint8_t shape;        // SHAPE_*: container of the hour wedge
  uint8_t show_ring;    // outline of the hour container
  uint8_t min_circle;   // rectangular watches: keep the minute wedge inside a circle as wide as the screen
  uint8_t min_ring;     // outline of that circle
} Settings;

#define RAMP_LOG 0
#define RAMP_LINEAR 1

static Window *s_window;
static Layer *s_canvas_layer;
static Settings s_settings;

// ----------------------------------------------------------------------------
// Fixed-point angle from 12 o'clock, clockwise, 0..TRIG_MAX_ANGLE-1
// ----------------------------------------------------------------------------

// atan(n/d) for 0 <= n <= d, d > 0, returned in trig angle units (0..8192 = 0..45 deg)
static int32_t oct_angle(int32_t n, int32_t d) {
  int32_t t = (n << 14) / d;                              // Q14, 0..16384
  int32_t t2 = (t * t) >> 14;
  int32_t f = (t * (20387 - ((4003 * t2) >> 14))) >> 14;  // ~atan(t) / (pi/4), Q14
  return f >> 1;
}

// angle from north for ax, ay >= 0, result 0..16384
static int32_t north_angle(int32_t ax, int32_t ay) {
  if (ax == 0 && ay == 0) return 0;
  if (ax <= ay) return oct_angle(ax, ay);
  return 16384 - oct_angle(ay, ax);
}

// dx right, dy down (screen coordinates)
static int32_t clock_angle(int32_t dx, int32_t dy) {
  int32_t ax = dx < 0 ? -dx : dx;
  int32_t up = -dy;
  int32_t a;
  if (up >= 0) {
    a = north_angle(ax, up);
  } else {
    a = 32768 - north_angle(ax, -up);
  }
  if (dx < 0) a = TRIG_MAX_ANGLE - a;
  return a;
}

// ----------------------------------------------------------------------------
// Dithering
// ----------------------------------------------------------------------------

// 8x8 Bayer threshold, 0..252
static inline int bayer8(int x, int y) {
  int a = x ^ y;
  int v = ((y & 1) << 5) | ((a & 1) << 4) | ((y & 2) << 2) |
          ((a & 2) << 1) | ((y & 4) >> 1) | ((a & 4) >> 2);
  return v * 4;
}

static inline uint8_t dither_level(int value, int thr) {
  int l = (value * 3 + thr) / 255;
  return l > 3 ? 3 : l;
}

static inline uint8_t solid_color(const uint8_t *rgb) {
  return 0xC0 | (((rgb[0] + 42) / 85) << 4) | (((rgb[1] + 42) / 85) << 2) | ((rgb[2] + 42) / 85);
}

// ----------------------------------------------------------------------------
// Drawing
// ----------------------------------------------------------------------------

// Opacity (0..255) of a disc at `dist` trig-angle units from its hand, going the way it fades
static inline int disc_opacity(const uint8_t *lut, int32_t dist) {
  const int i = dist >> 8;
  return i < DISC_RAMP_STEPS ? lut[i] : 0;
}

static void canvas_update_proc(Layer *layer, GContext *ctx) {
  GRect bounds = layer_get_bounds(layer);
  const int cx = bounds.size.w / 2;
  const int cy = bounds.size.h / 2;
  const int narrow = bounds.size.w < bounds.size.h ? bounds.size.w : bounds.size.h;
  const int dial_radius = (narrow * CONTAINER_NUM) / (CONTAINER_DEN * 2);
  const int radius2 = dial_radius * dial_radius;
  const int min_radius = narrow / 2;
  const int min_radius2 = min_radius * min_radius;

  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  if (!t) return;

  const int32_t min_angle = (t->tm_min * TRIG_MAX_ANGLE) / 60;
  const int32_t hour_angle = (((t->tm_hour % 12) * 60 + t->tm_min) * TRIG_MAX_ANGLE) / 720;

  const uint8_t *hc = s_settings.hour_rgb;
  const uint8_t *mc = s_settings.min_rgb;
  const uint8_t *lut = s_settings.ramp == RAMP_LINEAR ? DISC_LUT_LINEAR : DISC_LUT_LOG;
  const uint8_t ring_px = solid_color(hc);
  const uint8_t face_px = 0xFF;  // white
  const bool rect = s_settings.shape == SHAPE_RECT;
  const bool ring = s_settings.show_ring;
#if defined(PBL_ROUND)
  const bool min_circle = false;  // the screen is already a circle
  const bool min_ring = false;
#else
  const bool min_circle = s_settings.min_circle;
  const bool min_ring = min_circle && s_settings.min_ring;
#endif
  const uint8_t min_ring_px = solid_color(mc);

  // With a circular minute area the hour area is a circle or a true square, never a tall rectangle
  int half_w = (bounds.size.w * CONTAINER_NUM) / (CONTAINER_DEN * 2);
  int half_h = (bounds.size.h * CONTAINER_NUM) / (CONTAINER_DEN * 2);
  if (min_circle) half_h = half_w = (narrow * CONTAINER_NUM) / (CONTAINER_DEN * 2);

  GBitmap *fb = graphics_capture_frame_buffer(ctx);
  if (!fb) return;
  const GRect fb_bounds = gbitmap_get_bounds(fb);

  for (int y = fb_bounds.origin.y; y < fb_bounds.origin.y + fb_bounds.size.h; y++) {
    GBitmapDataRowInfo row = gbitmap_get_data_row_info(fb, y);
    const int dy = y - cy;
    for (int x = row.min_x; x <= row.max_x; x++) {
      const int dx = x - cx;
      const int adx = dx < 0 ? -dx : dx;
      const int ady = dy < 0 ? -dy : dy;
      const int r2 = dx * dx + dy * dy;
      bool inside;
      bool on_ring = false;
      if (rect) {
        inside = adx <= half_w && ady <= half_h;
        on_ring = ring && inside && (adx == half_w || ady == half_h);
      } else {
        inside = r2 <= radius2;
        int d = r2 - radius2;
        on_ring = ring && (d < 0 ? -d : d) <= dial_radius;
      }

      if (on_ring) {
        row.data[x] = ring_px;
        continue;
      }

      if (min_ring) {
        int d = r2 - min_radius2;
        if ((d < 0 ? -d : d) <= min_radius) {
          row.data[x] = min_ring_px;
          continue;
        }
      }

      // The minute wedge is limited to its own circle if enabled
      if (min_circle && r2 > min_radius2) {
        row.data[x] = face_px;
        continue;
      }

      // The hour wedge never leaves its container; the minute wedge runs on past it
      const int32_t theta = clock_angle(dx, dy);

      // Each disc is a conic gradient: 100% opaque at its hand, fading to 0% over 225
      // degrees and staying clear for the rest of the turn. The hour disc fades clockwise,
      // the minute disc counter-clockwise.
      int op_h = 0;
      if (inside) {
        op_h = disc_opacity(lut, (theta - hour_angle) & (TRIG_MAX_ANGLE - 1));
      }
      const int op_m = disc_opacity(lut, (min_angle - theta) & (TRIG_MAX_ANGLE - 1));

      // Layered like real translucent discs: the hour disc over the white face,
      // then the minute disc over that
      const int thr = bayer8(x, y);
      uint8_t lv[3];
      for (int i = 0; i < 3; i++) {
        int tone = 255 + ((hc[i] - 255) * op_h) / 255;
        tone += ((mc[i] - tone) * op_m) / 255;
        lv[i] = dither_level(tone, thr);
      }
      row.data[x] = 0xC0 | (lv[0] << 4) | (lv[1] << 2) | lv[2];
    }
  }

  graphics_release_frame_buffer(ctx, fb);
}

// ----------------------------------------------------------------------------
// Settings
// ----------------------------------------------------------------------------

static int tuple_to_int(const Tuple *tuple) {
  if (tuple->type == TUPLE_CSTRING) return atoi(tuple->value->cstring);
  return (int)tuple->value->int32;
}

// Clay sends a colour as 0xRRGGBB
static void set_rgb(uint8_t *rgb, int hex) {
  rgb[0] = (hex >> 16) & 0xFF;
  rgb[1] = (hex >> 8) & 0xFF;
  rgb[2] = hex & 0xFF;
}

static void validate_settings(void) {
  if (s_settings.ramp > RAMP_LINEAR) s_settings.ramp = RAMP_LOG;
  if (s_settings.shape > SHAPE_RECT) s_settings.shape = SHAPE_CIRCLE;
  s_settings.show_ring = s_settings.show_ring ? 1 : 0;
  s_settings.min_circle = s_settings.min_circle ? 1 : 0;
  s_settings.min_ring = s_settings.min_ring ? 1 : 0;
}

static void inbox_received(DictionaryIterator *iter, void *context) {
  Tuple *t;
  if ((t = dict_find(iter, MESSAGE_KEY_HOURCOLOR))) set_rgb(s_settings.hour_rgb, tuple_to_int(t));
  if ((t = dict_find(iter, MESSAGE_KEY_MINCOLOR))) set_rgb(s_settings.min_rgb, tuple_to_int(t));
  if ((t = dict_find(iter, MESSAGE_KEY_RAMP))) s_settings.ramp = tuple_to_int(t);
  if ((t = dict_find(iter, MESSAGE_KEY_SHAPE))) s_settings.shape = tuple_to_int(t);
  if ((t = dict_find(iter, MESSAGE_KEY_MINCIRCLE))) s_settings.min_circle = tuple_to_int(t) ? 1 : 0;
  if ((t = dict_find(iter, MESSAGE_KEY_MINRING))) s_settings.min_ring = tuple_to_int(t) ? 1 : 0;
  if ((t = dict_find(iter, MESSAGE_KEY_RING))) s_settings.show_ring = tuple_to_int(t) ? 1 : 0;
  validate_settings();
  persist_write_data(SETTINGS_KEY, &s_settings, sizeof(s_settings));
  if (s_canvas_layer) layer_mark_dirty(s_canvas_layer);
}

static void load_settings(void) {
  s_settings = (Settings) {
    .hour_rgb = {130, 135, 145},  // Silver
    .min_rgb = {0, 0, 0},         // Black
    .ramp = RAMP_LOG,
    .shape = SHAPE_CIRCLE,
    .show_ring = 1,
    .min_circle = 0,
    .min_ring = 1,
  };
  if (persist_exists(SETTINGS_KEY)) {
    persist_read_data(SETTINGS_KEY, &s_settings, sizeof(s_settings));
  }
  validate_settings();
}

// ----------------------------------------------------------------------------
// Lifecycle
// ----------------------------------------------------------------------------

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
  if (s_canvas_layer) layer_mark_dirty(s_canvas_layer);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  s_canvas_layer = layer_create(layer_get_bounds(root));
  layer_set_update_proc(s_canvas_layer, canvas_update_proc);
  layer_add_child(root, s_canvas_layer);
}

static void window_unload(Window *window) {
  layer_destroy(s_canvas_layer);
  s_canvas_layer = NULL;
}

static void init(void) {
  load_settings();

  s_window = window_create();
  window_set_background_color(s_window, GColorWhite);
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);

  tick_timer_service_subscribe(MINUTE_UNIT, tick_handler);

  app_message_register_inbox_received(inbox_received);
  app_message_open(128, 128);
}

static void deinit(void) {
  tick_timer_service_unsubscribe();
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
  return 0;
}
